[project]
name = "app_agent"
version = "0.1.0"
description = "Agent which can call tools. Tools can be provided locally or can be fetched from different MCP servers"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
